import os
from mistralai import Mistral
from services.policy_recommendation_service.schemas.policy_request import PolicyRequest

# =========================
# Client Initialization
# =========================

api_key = os.environ.get("MISTRAL_API_KEY")
if not api_key:
    raise EnvironmentError("MISTRAL_API_KEY is not set")

client = Mistral(api_key=api_key)

# =========================
# Web Search Agent
# =========================

websearch_agent = client.beta.agents.create(
    model="mistral-medium-2505",
    name="Policy Websearch Agent",
    description="Web-grounded agent for Indian health insurance recommendations.",
    instructions="""
You are a Health Insurance Research Assistant specializing in the Indian insurance market.

STRICT RULES (MANDATORY):
- You MUST use web_search for all factual information.
- NEVER invent premiums, benefits, room rent rules, hospital counts, or claim settlement ratios.
- If data varies, explicitly say "varies by profile / policy wording".
- Generic explainer articles CANNOT justify plan-level benefits.
- EACH policy MUST have its own cited sources.

OUTPUT FORMAT (MANDATORY):

1. Comparison table with columns:
   - Insurer
   - Plan Name
   - Key Benefits
   - PED Waiting Period
   - Room Rent Policy
   - Indicative Premium Range
   - Best Suited For
   - Sources (per policy)

2. Recommendation Summary (short)

3. Disclaimer

SOURCE RULES:
- Prefer official insurer product pages or brochures
- Aggregators allowed only for comparison
- Cite sources per policy (not pooled)

Tone: neutral, factual, compliance-safe.
""",
    tools=[{"type": "web_search"}],
    completion_args={
        "temperature": 0.2,
        "top_p": 0.9,
    },
)

# =========================
# Query Builder
# =========================

def build_query(request: PolicyRequest) -> str:
    return f"""
User Profile:
- Ages: {', '.join(map(str, request.ages))}
- Policy Type: {request.individual_or_family}
- City: {request.city}
- Pre-existing Diseases: {', '.join(request.pre_existing_diseases) if request.pre_existing_diseases else 'None'}
- Desired Sum Insured: ₹{request.desired_sum_insured:,}
- Budget: ₹{request.budget:,}
- Preference: {request.preference} (subject to policy terms)

Find the TOP 3–5 most suitable health insurance policies in India.
Use web_search and cite sources PER POLICY.
"""

# =========================
# Recommendation Function
# =========================

def get_policy_recommendations(request: PolicyRequest) -> str:
    try:
        response = client.beta.conversations.start(
            agent_id=websearch_agent.id,
            inputs=build_query(request),
        )

        if not hasattr(response, "outputs"):
            return "No response generated by agent."

        final_text = []

        for output in response.outputs:
            # Collect only final assistant messages
            if output.type == "message.output":
                for chunk in output.content:
                    if hasattr(chunk, "text"):
                        final_text.append(chunk.text)

        if not final_text:
            return "No recommendations found."

        return "\n".join(final_text)

    except Exception as e:
        return f"Error generating policy recommendations: {str(e)}"
